/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mzp_woliveira' at '6/21/16 1:58 PM' with Gradle 2.14
 *
 * @author mzp_woliveira, @date 6/21/16 1:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
